[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "tsunami-notes"
version = "0.1.0"
description = "Private, secure, encrypted notes app for Ubuntu."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "rich>=13.0.0",
    "textual>=0.40.0",
    "pygame>=2.0.0",
]

[project.scripts]
tsunami = "tsunami_notes.notes:main"

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "."
module-name = "tsunami_notes.crypto"

[tool.black]
target-version = ["py310"]

[tool.pylint.master]
extension-pkg-allow-list = "tsunami_notes.crypto"
